export const STADIUM_INFO = [
    {   
        id: 1,
        ballpark: "American Family Field",
        teamName: "Milwaukee Brewers",
        division: "National League Central",
        state: "Wisconsin",
        city: "Milwaukee",
        zipCode: 53214,
        yearOpened: 2001,
        capacity: "41,900",
        cost: "$382 Million",
        style: {background: "rgb(33,53,88)"},
        url: "https://www.jsonline.com/gcdn/presto/2023/02/14/PMJS/0b76729c-b413-4ee1-a295-6920244b81d0-American_Family_Field_1.JPG"
      },
      {
        id: 2,
        ballpark: "Angel Stadium",
        teamName: "Los Angeles Angels",
        division: "American League West",
        state: "California",
        city: "Anaheim",
        zipCode: 92806,
        yearOpened: 1966,
        capacity: "45,050",
        cost: "$24 Million",
        style: {background: "rgb(195,61,83)"},
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Angelstadiumfront2021.jpg/2880px-Angelstadiumfront2021.jpg"
      },
      {
        id: 3,
        ballpark: "Busch Stadium",
        teamName: "St. Louis Cardinals",
        division: "National League Central",
        state: "Missouri",
        city: "St. Louis",
        zipCode: 63102,
        yearOpened: 2006,
        capacity: "43,975",
        cost: "$411 Million",
        style: {background: "rgb(206,65,89)"},
        url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Busch_Stadium_9-21-14.jpg"
      },
      {
        id: 4,
        ballpark: "Camden Yards",
        teamName: "Baltimore Orioles",
        division: "American League East",
        state: "Maryland",
        city: "Baltimore",
        zipCode: 21201,
        yearOpened: 1992,
        capacity: "45,971",
        cost: "$110 Million",
        style: {background: "rgb(209,96,51)"},
        url: "https://d2uqqhmijd5j2z.cloudfront.net/files/130133/original/Camden_Yards_entrance.JPG?1482169604"
      },
      {
        id: 5,
        ballpark: "Chase Field",
        teamName: "Arizona Diamondbacks",
        division: "National League West",
        state: "Arizona",
        city: "Phoenix",
        zipCode: 85004,
        yearOpened: 1998,
        capacity: "48,633",
        cost: "$354 Million",
        style: {background: "rgb(156,41,59)"},
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Reserve_A-10_Warthogs_Flyover_2023_World_Series_%288099146%29.jpg/2560px-Reserve_A-10_Warthogs_Flyover_2023_World_Series_%288099146%29.jpg"
      },
      {
        id: 6,
        ballpark: "Citi Field",
        teamName: "New York Mets",
        division: "National League East",
        state: "New York",
        city: "Flushing",
        zipCode: 11368,
        yearOpened: 2009,
        capacity: "42,000",
        cost: "$632 Million",
        style: {background: "rgb(236,101,48)"},
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Citi_Field_%2848613685207%29.jpg/2880px-Citi_Field_%2848613685207%29.jpg"
      },
      {
        id: 7,
        ballpark: "Citizens Bank Park",
        teamName: "Philadelphia Phillies",
        division: "National League East",
        state: "Pennsylvania",
        city: "Philadelphia",
        zipCode: 19148,
        yearOpened: 2004,
        capacity: "43,035",
        cost: "$458 Million",
        style: {background: "rgb(213,53,52)"},
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Citizens_Bank_Park_2021.jpg/2560px-Citizens_Bank_Park_2021.jpg"
      },
      {
        id: 8,
        ballpark: "Comerica Park",
        teamName: "Detroit Tigers",
        division: "American League Central",
        state: "Michigan",
        city: "Detroit",
        zipCode: 48201,
        yearOpened: 2000,
        capacity: "41,574",
        cost: "$300 Million",
        style: {background: "rgb(21,43,83)"},
        url: "https://i0.wp.com/keeonsports.com/wp-content/uploads/2022/03/comerica.jpg?w=899&ssl=1"
      },
      {
        id: 9,
        ballpark: "Citizens Bank Park",
        teamName: "Colorado Rockies",
        division: "National League West",
        state: "Colorado",
        city: "Denver",
        zipCode: 80205,
        yearOpened: 1995,
        capacity: "50,398",
        cost: "$115 Million",
      },
      {
        id: 10,
        ballpark: "Dodger Stadium",
        teamName: "Los Angeles Dodgers",
        division: "National League West",
        state: "California",
        city: "Los Angeles",
        zipCode: 90012,
        yearOpened: 1962,
        capacity: "56,000",
        cost: "$23 Million",
      },
  ];